### ISSUE TITLE
The uploaded files are deleted by accidentally posting a removefile request immediately after submitting a runtask with uploaded files

### ISSUE THREAD

**Issue by zhangzhen** [rowanwins/vue-dropzone#217]
- Vue2-dropzone Version:2.3.5
- Node Version : 6.11.4
- NPM Version : 3.10.10
- OS: Ubuntu 16.04

### Description:
vue-dropzone is used to upload files. Frontend code is built with webpack and deployed to server with docker-compose. The uploaded files are deleted by accidentally posting a removefile request immediately after submitting a runtask with uploaded files. Can someone help me to avoid unnecessary deleting?

```
    destroyed: function() {
      document.querySelectorAll('input.dz-hidden-input').forEach(function (elem) { elem.parentNode.removeChild(elem) })
    }
```

The code above may issue the removefile request.

**Comment by lomholdt** [comment]
I am experiencing the same issue. A `vdropzone-removed-file` event is emitted when the component is destroyed. Since i'm listening to the event and deleting images on the server all the images get deleted. I dont think that's expected behaviour.

**Comment by rowanwins** [comment]
Hi @lomholdt 

This is fixed in v3 which I will hopefully release some time in the coming week. Feel free to take a look at the `v3` [branch](https://github.com/rowanwins/vue-dropzone/tree/version3) if you'd like a more immediate fix.

**Comment by lomholdt** [comment]
Hi' @rowanwins. Sounds, and looks great! Thanks a ton! I will add the fix manually for now until the new version is out. Thanks again :)

**Comment by rowanwins** [comment]
Hi @lomholdt & @zhangzhen 

V3 is now released for feel free to [check it out](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation), it contains a property to cancel the destroy event so hopefully it helps.

**Comment by lomholdt** [comment]
Thanks! :) Much appreciated.

**Comment by middle21** [comment]
Problem still exists in 3.6.0. Hitting the back button that fires the following code 
`$router.go(-1)` on a button click destroys the vue2 dropzone component triggering unwanted calls to @vdropzone-removed-file="vremoved" removing the uploaded files.

Any solution yet ? Thanks.
